#! /bin/bash

# (c) Thomas Lange, 2001-2008, lange@debian.org

error=0 ; trap "error=$((error|1))" ERR

# a list of modules which are loaded at boot time
fcopy -i /etc/modules
for module in $MODULESLIST; do
    ainsl -a $target/etc/modules "^$module$"
done

fcopy /etc/hostname || echo $HOSTNAME     > $target/etc/hostname
echo $TIMEZONE    > $target/etc/timezone
ln -fs /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime

fcopy -iM /etc/hosts /etc/motd

# set root password
echo "root:$ROOTPW" | $ROOTCMD chpasswd --encrypted
# make /root accessible only by root
chmod 0700 $target/root
chown root:root $target/root
# copy default dotfiles for root account
fcopy -ir /root

# create keyboard layout table
$ROOTCMD bash -c "echo 'console-data console-data/keymap/full select $KEYMAP' | debconf-set-selections"
$ROOTCMD install-keymap $KEYMAP || true
# dumpkeys | gzip -9f >$target/etc/console/boottime.kmap.gz

[ ! -d $target/root/.ssh ] && mkdir -p $target/root/.ssh

cat<<EOF? $target/root/.ssh/authorized_keys2
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDt1d4yn+Ka1a5BrnwJ8QI0SiuxLSyH2RfctoPGWZzlxElm0L22DnEj3spMpR8m4K6ErUFz8ICRHyJ+0bj3KqeFUfVc1EVZbaY6B9/QdaSSm9KZM5Pew+SMoH4lvAV0BSX5DcHwln83rjKP5/fTnNw28OwvJ5MCd0GS2y/7mTXsWdH+dARYF6gmQQfwJ+cVnjNUxJlQtZY6I0XniDy7ZYrWLecYx409NlQBdI5ZLtFW4SLbDKarHVg4wf82qjc9xvErMLRLrgQ6LIkdCK8HQq506C26fEF2PHEkgMboelNwi8aagGx4Ce0zFq3xO45pxQqR/9J+RVI1anZX0tIm20ul jameswhite@Jamess-MacBook-Pro.local
EOF

chmod 700 $target/root/.ssh
chmod 400 $target/root/.ssh/authorized_keys

exit $error
