#! /bin/bash

error=0 ; trap "error=$((error|1))" ERR

cat<<EOF > $target/etc/apt/sources.list
deb http://ftp.us.debian.org/debian/ wheezy main non-free
deb http://security.debian.org/ wheezy/updates main non-free
deb-src http://ftp.us.debian.org/debian/  wheezy main
EOF

cat<<EOF > $target/etc/apt/preferences
Package: *
Pin: release a=wheezy
Pin-Priority: 500

Package: *
Pin: release a=wheezy-backports
Pin-Priority: 200
EOF

exit $error
