#! /bin/bash
[ -z "${target}" ] && export target='/target'
KERNEL_VERSION=$(/bin/ls $target/lib/modules)

error=0 ; trap "error=$((error|1))" ERR
if [ ! -d ${target}/boot/grub ];then
    mkdir -p ${target}/boot/grub
fi

cat<<EOF >${target}/boot/grub/grub.cfg
# 19200 8n1
#serial --unit=0 --speed=19200 --word=8 --parity=no --stop=1
set timeout=0
set default=0
menuentry "soekris ro-root on cryptoloop" {
        set root=(hd0,1)
        linux /vmlinuz-${KERNEL_VERSION} root=/dev/mapper/crypt_dev_sda2 ro console=ttyS0,19200n8
        initrd /initrd.img-${KERNEL_VERSION}
}
EOF
echo -n "Installing the GRUB boot loader"
/usr/sbin/grub-install --root-directory=${target} /dev/sda >> ${LOG_FILE} 2>&1 &
spinner $!



exit $error
