#!/bin/bash

# should these be libpam-ldapd libnss-ldapd now?
chroot ${target} /usr/bin/env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get -y -o DPkg::options::='--force-confdef' -o DPkg::options::='--force-confold' install libpam-ldap libnss-ldap ldap-utils sudo-ldap sssd-ldap autodir

/bin/cp $target/etc/default/autodir $target/etc/default/autodir.dist
/bin/cat<<EOF > $target/etc/default/autodir
RUN_AUTOHOME="yes"
RUN_AUTOGROUP="yes"
AUTOHOME_HOME=/home
AUTOGROUP_HOME=/group
AUTOHOME_TIMEOUT=660
AUTOGROUP_TIMEOUT=300
AUTOHOME_MODULE="/usr/lib/autodir/autohome.so"
AUTOGROUP_MODULE="/usr/lib/autodir/autogroup.so"
AUTOHOME_OPTIONS="realpath=/opt/auto/home,level=2,skel=/etc/skel"
AUTOGROUP_OPTIONS="realpath=/opt/auto/group,level=2"
#AUTOHOME_BACKUP="'/bin/tar cf /tmp/%N.tar.gz %L'"
#AUTOGROUP_BACKUP="'/bin/tar cf /tmp/%N.tar.gz %L'"
#AUTOHOME_BACKWAIT=600
#AUTOGROUP_BACKWAIT=600
#AUTOHOME_BACKPRI=30
#AUTOGROUP_BACKPRI=30
#AUTOHOME_MAXBACK=150
#AUTOGROUP_MAXBACK=150
EOF

cat<<EOF > $target/root/add_opt
#!/bin/bash
/usr/sbin/groupadd --gid 400 opt
/usr/sbin/useradd --uid 400 --gid 400 -m --home-dir /home/opt --comment "Optional Software Administrator" --shell /bin/bash opt
/bin/echo "opt:fai" | /usr/sbin/chpasswd
mkdir -p $target/home/opt/.ssh
chmod 750 $target/home/opt/.ssh
EOF

chmod 755 $target/root/add_opt
/usr/sbin/chroot $target /root/add_opt
/bin/rm $target/root/add_opt

cat<<EOF > $target/home/opt/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDt1d4yn+Ka1a5BrnwJ8QI0SiuxLSyH2RfctoPGWZzlxElm0L22DnEj3spMpR8m4K6ErUFz8ICRHyJ+0bj3KqeFUfVc1EVZbaY6B9/QdaSSm9KZM5Pew+SMoH4lvAV0BSX5DcHwln83rjKP5/fTnNw28OwvJ5MCd0GS2y/7mTXsWdH+dARYF6gmQQfwJ+cVnjNUxJlQtZY6I0XniDy7ZYrWLecYx409NlQBdI5ZLtFW4SLbDKarHVg4wf82qjc9xvErMLRLrgQ6LIkdCK8HQq506C26fEF2PHEkgMboelNwi8aagGx4Ce0zFq3xO45pxQqR/9J+RVI1anZX0tIm20ul jameswhite@Jamess-MacBook-Pro.local
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLuHahxjD7lAWGpE1LLFXenj+90WcMBzZNdw1OuCqOR9ioJag/atjKRuV7e/SiZ2ITtArjsz/YRCsgdaB34YTovFVf5U59uGuiawfa2zpTk8TmojvpcNqNOll4kM6Fa280Uu89cy8aCANhPnnZC4l9YBuuemCDllFPvcUTkN5GpIr0eWEsI+ZbCW4jDsLsZHCFMJ0MbeRfJR1wqid+AgB3xeEIJulpqinWkx3IyGHDnG//A4AglXw7ndz0gxEeE1JAtvVX20CgZPFdRk4UivU8MtLffAh5G/gCYsDjKXHaZaswpvQAf3BcI1WuBqfA2KwP2GJLw93wmbb0euWCwJfYUobeedjxWUzscYzY5yCadPZla+FGEPCbTeRK525OxgRkxXRzW2Tlidba8wKI0xMJ66ZqizRV4wBJvEZDOI+s+kAuPEHR7RIHmagfEUUHQQFKOFxIsfBYnA5Bo12HVopEkbImQTJrAu0mwwChZD+TgOtfRLs35Cgn5uBbHGU+DKt47uMN/ZTWL/CaFX+mDv3fB1W3bB1b3g6GxpttHBtESddNXeeMY5TfT8ffMj/uOQ2aZWOwqFIlDqtvbuNxLCpjGGJKM0FFZMVq9JQ01aEF98oNNv0cwJ5fUNijndF3n7D1sfEo4mt/Fe2Ni7muusWAAjMs6BCP9cHRKj+Lgio/Yw== jameswhite@forseti.local
EOF
chown 400:400 $target/home/opt/.ssh/authorized_keys
chmod 640 $target/home/opt/.ssh/authorized_keys

# /bin/cp $target/etc/gdm3/daemon.conf $target/etc/gdm3/daemon.conf.dist
# /bin/sed -ie 's/\[security\]/[security]\nDisallowTCP=false/' $target/etc/gdm3/daemon.conf


# get rid of fat gnome title bars
# sed -i "/title_vertical_pad/s/value=\"[0-9]\{1,2\}\"/value=\"0\"/g" /usr/share/themes/Adwaita/metacity-1/metacity-theme-3.xml


/bin/mkdir -p $target/etc/ldap/ssl
/bin/cp $FAI/files/etc/ldap/ldap.conf.tpl $target/etc/ldap/ldap.conf.tpl
/bin/sed -e "s/~ANON_SECRET~/${ANON_SECRET}/g" $target/etc/ldap/ldap.conf.tpl > $target/etc/ldap/ldap.conf
/bin/cp $FAI/files/etc/ldap/ssl/domain_trustchain.pem $target/etc/ldap/ssl/domain_trustchain.pem
/bin/cp $FAI/files/etc/nsswitch.conf $target/etc/nsswitch.conf
(cd $target/etc; mv libnss-ldap.conf libnss-ldap.conf.dist; ln -s ldap/ldap.conf libnss-ldap.conf )
(cd $target/etc; mv pam_ldap.conf pam_ldap.conf.dist;       ln -s ldap/ldap.conf pam_ldap.conf )
