#!/bin/bash
error=0 ; trap "error=$((error|1))" ERR

cat<<EOF >/boot/setup
#!/bin/sh
cryptsetup --key-file=/boot/crypt_dev_sda2  luksOpen /dev/sda2 cryptoroot
lvm pvscan
lvm vgchange -a y vg0
# swapon /dev/mapper/vg0-swap
mount /dev/mapper/vg0-root /sysroot
mount /dev/mapper/vg0-home /sysroot/home
mount /dev/mapper/vg0-opt /sysroot/opt
mount /dev/mapper/vg0-tmp /sysroot/tmp
mount /dev/mapper/vg0-usr /sysroot/usr
mount /dev/mapper/vg0-var /sysroot/var
EOF
chmod 755 /boot/setup

cat<<EOF > /etc/dracut.conf.d/01-omit.conf
# omit_dracutmodules+=" btrfs lvm resume usrmount mdraid shutdown dracut-systemd systemd systemd-initrd systemd-networkd systemd-initrd "
omit_dracutmodules+=" btrfs resume usrmount mdraid shutdown dracut-systemd systemd systemd-initrd systemd-networkd systemd-initrd "
filesystems="nfs lockd ext4"
EOF

grep -q add_dracutmodules /etc/dracut.conf || echo "add_dracutmodules+=\"lvm crypt\"" >> /etc/dracut.conf.d/10-crypt.conf
grep -q install_items     /etc/dracut.conf || echo "install_items+=\"/boot/crypt_dev_sda2 /boot/setup\"" >> /etc/dracut.conf.d/10-crypt.conf

cp /boot/{System.map,config,vmlinuz}-$(uname -r) /target/boot
cp /tmp/fai/crypt_dev_sda2 /boot
cp /tmp/fai/crypt_dev_sda2 /target/boot
# sed -e 's/\/tmp\/fai/\/boot/' /target/etc/crypttab > /etc/crypttab

dracut --force -M /target/boot/initramfs-$(uname -r).img $(uname -r)

# lsinitrd /target/boot/initramfs-$(uname -r).img | egrep "(crypttab|crypt_dev|setup)"

rm ${target}/etc/crypttab

exit $error
