#!/bin/bash
error=0 ; trap "error=$((error|1))" ERR

# install grub on the target
chroot ${target} /usr/bin/env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get -y -o DPkg::options::='--force-confdef' -o DPkg::options::='--force-confold' install grub2 grub2-common

# tell grub about our crypt device
grep -q GRUB_CMDLINE_LINUX     /etc/default/grub || echo "GRUB_CMDLINE_LINUX=\"cryptdevice=/dev/sda2:lvm\""       >> ${target}/etc/default/grub
grep -q GRUB_CRYPTODISK_ENABLE /etc/default/grub || echo "GRUB_CRYPTODISK_ENABLE=y  # This option worked on void" >> ${target}/etc/default/grub
grep -q GRUB_ENABLE_CRYPTODISK /etc/default/grub || echo "GRUB_ENABLE_CRYPTODISK=y  # This one worked on Arch. It is safe to include both just in case " >> ${target}/etc/default/grub

# install grub on the root device 
grub-install --root-directory=${target} /dev/sda

# generate the grub.cfg
chroot ${target} /usr/sbin/update-grub

# update-grub just calls:
# chroot ${target} grub-mkconfig -o /boot/grub/grub.cfg

exit $error
