#!/bin/bash
error=0 ; trap "error=$((error|1))" ERR

# install grub on the target
chroot ${target} /usr/bin/env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get -y -o DPkg::options::='--force-confdef' -o DPkg::options::='--force-confold' install grub2 grub2-common

# tell grub about our crypt device
# GRUB_CMDLINE_LINUX="cryptdevice=/dev/sda2:lvm rd.auto=1"
cmdline_linux=$(grep GRUB_CMDLINE_LINUX ${target}/etc/default/grub | sed -e 's/^[^"]*"//' -e 's/"[^"]*//g' )
echo "${cmdline_linux}" | grep -q "cryptdevice=/dev/sda2:lvm" || cmdline_linux="${cmdline_linux} cryptdevice=/dev/sda2:lvm"
sed -i -e 's/GRUB_CMDLINE_LINUX=".*"/GRUB_CMDLINE_LINUX="${cmdline_linux}"/' ${target}/etc/default/grub
grep -q GRUB_CRYPTODISK_ENABLE ${target}/etc/default/grub || echo "GRUB_CRYPTODISK_ENABLE=y  # This option worked on void" >> ${target}/etc/default/grub
grep -q GRUB_ENABLE_CRYPTODISK ${target}/etc/default/grub || echo "GRUB_ENABLE_CRYPTODISK=y  # This one worked on Arch. It is safe to include both just in case " >> ${target}/etc/default/grub

# install grub on the root device 
grub-install --root-directory=${target} /dev/sda

# generate the grub.cfg
chroot ${target} /usr/sbin/update-grub

# update-grub just calls:
# chroot ${target} grub-mkconfig -o /boot/grub/grub.cfg

exit $error
