#!/bin/sh

PREREQ=""
prereqs(){
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
    ;;
esac

# Begin real processing below this line
[ ! -d ${DESTDIR}/boot ] && mkdir -p ${DESTDIR}/boot

# BUSYBOX=y in the initramfs.conf doesn't work
[ ! -d ${DESTDIR}/bin ] && mkdir -p ${DESTDIR}/bin
cp /usr/bin/busybox ${DESTDIR}/bin

exit 0
