#! /bin/bash
export PATH="/usr/local/sbin:/usr/local/bin:/usr/lib/fai:/usr/sbin:/usr/bin:/sbin:/bin"
[ -z "${target}" ] && export target='/target'

KERNEL_VERSION=$(/bin/ls $target/lib/modules)

error=0 ; trap "error=$((error|1))" ERR

if [ ! -d ${target}/boot/grub ];then
    mkdir -p ${target}/boot/grub
fi

cat<<EOF >${target}/boot/grub/grub.cfg
set timeout=0
set default=0
menuentry "${HOSTNAME}" ro-root on cryptoloop" {
        set root=(hd1,0)
        linux /vmlinuz-${KERNEL_VERSION} root=/dev/mapper/vg0-root ro hostname=${HOSTNAME}
        initrd /initrd.img-${KERNEL_VERSION}
}
EOF

echo -n "Installing the GRUB boot loader"
grub-mkdevicemap --device-map=/target/boot/grub/device.map
grub-install --root-directory=/target "(hd1)"
grub-install --root-directory=/target "(hd2)"
exit $error
