#!/bin/bash

sed -i -e "s/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet\"/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet hostname=${HOSTNAME}\"/" ${target}/etc/default/grub
echo -n "Installing the GRUB boot loader"

grub-mkdevicemap --device-map=/target/boot/grub/device.map
for device in $(cat /target/boot/grub/device.map | grep -v "(fd0)" |awk '{print $1}'); do
  grub-install --root-directory=${target} "${device}"
  sleep 9000
done
exit $error
