#! /bin/bash

# copyright Thomas Lange 2001-2007, lange@debian.org

error=0 ; trap "error=$((error|1))" ERR

cat<<EOF > ${target}/etc/network/interfaces.d/eth0
auto eth0
# iface eth0 inet dhcp
iface eth0 inet static
    address 10.252.0.31/24
    gateway 10.252.0.1
EOF

# set bios clock
if [ $do_init_tasks -eq 1 ] ; then
    case "$UTC" in
       no|"") hwopt="--localtime" ;;
       yes)   hwopt="--utc"       ;;
    esac
    $ROOTCMD hwclock $hwopt --systohc || true
fi

fcopy -i /etc/apt/sources.list

exit $error

