#! /bin/bash

error=0 ; trap "error=$((error|1))" ERR

TARGET="/target"
cat<<EOF> ${TARGET}/etc/apt/sources.list
deb http://deb.debian.org/debian/ bookworm main non-free-firmware contrib
deb-src http://deb.debian.org/debian/ bookworm main non-free-firmware contrib
EOF
chroot ${TARGET} apt-get update


exit $error
