#!/bin/bash
# rm -rf /target/tmp/initrd.d/; mkdir -p /target/tmp/initrd.d/ ; (cd /target/tmp/initrd.d/ ; cat /target/boot/initrd.img-4.19.0-8-amd64 | gzip -dc | cpio -idm); ls -l /target/tmp/initrd.d; cat /target/tmp/initrd.d/boot/setup
error=0 ; trap "error=$((error|1))" ERR
[ -z "${target}" ] && target='/target'

# install dracut on the target
chroot ${target} /usr/bin/env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get -y -o DPkg::options::='--force-confdef' -o DPkg::options::='--force-confold' install dracut

cat<<EOF >/boot/setup
#!/bin/sh
set -eo pipefail
[ ! -d /mnt ] && mkdir -p /mnt
mount -t ext3 /dev/sda1 /mnt
[ ! -h /dev/mapper/crypt_dev_sda2 ] && cryptsetup --key-file=/mnt/\$(hostname -s)/crypt_dev_sda2  luksOpen /dev/sda2 cryptoroot
[ -f /etc/lvm/lvm.conf ] && rm /etc/lvm/lvm.conf
lvm pvscan
lvm vgscan
lvm lvscan
lvm vgchange -ay
# swapon /dev/mapper/vg0-swap
mount | grep sysroot || mount -t ext4 /dev/mapper/vg0-root /sysroot || exit 1
mount | grep opt     || mount -t ext4 /dev/mapper/vg0-opt /sysroot/opt
mount | grep tmp     || mount -t ext4 /dev/mapper/vg0-tmp /sysroot/tmp
mount | grep var     || mount -t ext4 /dev/mapper/vg0-var /sysroot/var
umount /mnt && mount /dev/sda1 /sysroot/boot
exit 0
EOF
chmod 755 /boot/setup

cat<<EOF > /etc/dracut.conf.d/01-omit.conf
# omit_dracutmodules+=" btrfs lvm resume usrmount mdraid shutdown dracut-systemd systemd systemd-initrd systemd-networkd systemd-initrd "
omit_dracutmodules+=" btrfs resume usrmount mdraid shutdown dracut-systemd systemd systemd-initrd systemd-networkd systemd-initrd "
filesystems="nfs lockd ext4"
EOF

grep -q add_dracutmodules /etc/dracut.conf || echo "add_dracutmodules+=\"lvm crypt\"" >> /etc/dracut.conf.d/10-crypt.conf
grep -q install_items     /etc/dracut.conf || echo "install_items+=\"/boot/$(hostname -s)/crypt_dev_sda2 /boot/setup\"" >> /etc/dracut.conf.d/10-crypt.conf

cp /boot/{System.map,config,vmlinuz}-$(uname -r) ${target}/boot
cp ${target}/boot/$(hostname -s)/crypt_dev_sda2 /boot

[ ! -d /usr/lib/dracut/modules.d/91local ] && mkdir -p /usr/lib/dracut/modules.d/91local
cat<<EOF > /usr/lib/dracut/modules.d/91local/module-setup.sh
#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
check() {
return 0
}

depends() {
return 0
}

install() {
inst_hook initqueue/settled 91 "\$moddir/mount-local.sh"
}
EOF

cat<<EOF > /usr/lib/dracut/modules.d/91local/mount-local.sh
#!/bin/sh
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
set -eo pipefail
mount_local()
{
[ ! -d /mnt ] && mkdir -p /mnt
mount -t ext3 /dev/sda1 /mnt
cryptsetup --key-file=/mnt/\$(hostname -s)/crypt_dev_sda2  luksOpen /dev/sda2 cryptoroot
[ -f /etc/lvm/lvm.conf ] && rm /etc/lvm/lvm.conf
lvm pvscan
lvm vgscan
lvm lvscan
lvm vgchange -ay
mount -t ext4 /dev/mapper/vg0-root /sysroot
mount -t ext4 /dev/mapper/vg0-opt /sysroot/opt
mount -t ext4 /dev/mapper/vg0-tmp /sysroot/tmp
mount -t ext4 /dev/mapper/vg0-var /sysroot/var
umount /mnt && mount /dev/sda1 /sysroot/boot
}

mount_local
EOF
chmod 755 /usr/lib/dracut/modules.d/91local/*.sh

cat<<EOF >> /etc/dracut.conf
tmpdir=${target}/var/tmp
EOF

# copy the relevant files to the ${target} so regenerating the initramfs on the new host doesn't render it unbootable
cp /etc/dracut.conf.d/01-omit.conf ${target}/etc/dracut.conf.d/01-omit.conf
cp /etc/dracut.conf.d/10-crypt.conf ${target}//etc/dracut.conf.d/10-crypt.conf
[ ! -d ${target}/usr/lib/dracut/modules.d/91local ] && mkdir -p ${target}/usr/lib/dracut/modules.d/91local
cp -p /usr/lib/dracut/modules.d/91local/*.sh ${target}/usr/lib/dracut/modules.d/91local/


[ -f ${target}/boot/initrd.img-$(uname -r) ] && rm ${target}/boot/initrd.img-$(uname -r)
dracut --force -M ${target}/boot/initrd.img-$(uname -r) $(uname -r)

# lsinitrd ${target}/boot/initramfs-$(uname -r).img | egrep "(crypttab|crypt_dev|setup)"

rm ${target}/etc/crypttab

exit $error
