#!/bin/bash
# [ -d /target/tmp/initrd.d/ ] && rm -rf /target/tmp/initrd.d/; mkdir -p /target/tmp/initrd.d/ ; (cd /target/tmp/initrd.d/ ; cat /target/boot/initrd.img-4.19.0-8-amd64 | gzip -dc | cpio -idm); ls -l /target/tmp/initrd.d; cat /target/tmp/initrd.d/boot/setup-storage
error=0 ; trap "error=$((error|1))" ERR
[ -z "${target}" ] && target='/target'
[ -z "${config}" ] && config='/var/lib/fai/config'
files="${config}/files"
export files target config

# install a file from /var/lib/config/files/* to /target/*
finstall(){
  OWNER='root'
  GROUP='root'
  MODE='0644'
  unset SOURCE
  unset TARGET
  while [ ! -z "$*" ]; do
    case "$1" in
      "-m"|"--mode")
        MODE="$2"
        shift 2
      ;;
      "-o"|"--owner")
        OWNER="$2"
        shift 2
      ;;
      "-g"|"--group")
        GROUP="$2"
        shift 2
      ;;
      *)
        if [ -z "${SOURCE}" ]; then
          SOURCE="$1"
          shift 1
        else
          if [ -z "${TARGET}" ]; then
            TARGET="$1"
            shift 1
          else
            echo "Too many options: source(${SOURCE}) -> target(${TARGET}), $1 ?"
            exit 1
          fi
        fi
      ;;
    esac
  done
  [ -z "${TARGET}"] && TARGET="${SOURCE}"

  install -o "${OWNER}" -g "${GROUP}" -m "${MODE}" "${files}/${SOURCE}" "${target}/${TARGET}"
}

# install dracut on the target
# chroot ${target} /usr/bin/env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get -y -o DPkg::options::='--force-confdef' -o DPkg::options::='--force-confold' install dracut

finstall /etc/dracut.conf.d/01-omit.conf
finstall -m 0755 /boot/setup-storage
finstall -m 0755 /usr/lib/dracut/modules.d/91local/mount-local.sh
finstall -m 0755/usr/lib/dracut/modules.d/91local/module-setup.sh

# BOOT="$(mount | grep "/dev/sda1" | awk '{print $3}')"

# INSTALL_ITEMS="$(ls -1 ${BOOT}/$(hostname -s)/ | sed -e "s/.*\/$(hostname -s)\///" | tr '\n' ' ')"
# echo "install_items+=\"${INSTALL_ITEMS} /boot/setup-storage\"" >> /etc/dracut.conf.d/10-crypt.conf

# make ${target}/boot/${fqdn}, link hostname -s, localhost to it, copy the encryption keys to it
# (cd ${target}/boot; mkdir $(hostname); [ "$(hostname)" != "$(hostname -s)" ] && ln -s $(hostname) $(hostname -s); ln -s $(hostname) localhost);
# cp /tmp/fai/crypt* ${target}/boot/$(hostname)

# create a dracut.conf for our initial run
# cat<<EOF >> /etc/dracut.conf
# tmpdir=${target}/var/tmp
# EOF

# # copy the relevant files to the ${target} so regenerating the initramfs on the new host doesn't render it unbootable
# cp /boot/setup-storage                           ${target}/boot/setup-storage
# cp /boot/{System.map,config,vmlinuz}-$(uname -r) ${target}/boot
# cp /etc/dracut.conf.d/01-omit.conf               ${target}/etc/dracut.conf.d/01-omit.conf
# cp /etc/dracut.conf.d/10-crypt.conf              ${target}//etc/dracut.conf.d/10-crypt.conf
# [ ! -d ${target}/usr/lib/dracut/modules.d/91local ] && mkdir -p ${target}/usr/lib/dracut/modules.d/91local
# cp -p /usr/lib/dracut/modules.d/91local/*.sh     ${target}/usr/lib/dracut/modules.d/91local/
#
#
# # Run dracut and bake our initrd.img
# [ -f ${target}/boot/initrd.img-$(uname -r) ] && rm ${target}/boot/initrd.img-$(uname -r)
# dracut --force -M ${target}/boot/initrd.img-$(uname -r) $(uname -r)
#
# rm ${target}/etc/crypttab

exit $error
