#!/bin/bash
/bin/cp $target/etc/default/autodir $target/etc/default/autodir.dist
/bin/cat<<EOF > $target/etc/default/autodir
RUN_AUTOHOME="yes"
RUN_AUTOGROUP="yes"
AUTOHOME_HOME=/home
AUTOGROUP_HOME=/group
AUTOHOME_TIMEOUT=660
AUTOGROUP_TIMEOUT=300
AUTOHOME_MODULE="/usr/lib/autodir/autohome.so"
AUTOGROUP_MODULE="/usr/lib/autodir/autogroup.so"
AUTOHOME_OPTIONS="realpath=/opt/auto/home,level=2,skel=/etc/skel"
AUTOGROUP_OPTIONS="realpath=/opt/auto/group,level=2"
#AUTOHOME_BACKUP="'/bin/tar cf /tmp/%N.tar.gz %L'"
#AUTOGROUP_BACKUP="'/bin/tar cf /tmp/%N.tar.gz %L'"
#AUTOHOME_BACKWAIT=600
#AUTOGROUP_BACKWAIT=600
#AUTOHOME_BACKPRI=30
#AUTOGROUP_BACKPRI=30
#AUTOHOME_MAXBACK=150
#AUTOGROUP_MAXBACK=150
EOF

mkdir -p $target/root/.ssh
chmod 750 $target/root/.ssh
cat<<EOF > $target/root/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDt1d4yn+Ka1a5BrnwJ8QI0SiuxLSyH2RfctoPGWZzlxElm0L22DnEj3spMpR8m4K6ErUFz8ICRHyJ+0bj3KqeFUfVc1EVZbaY6B9/QdaSSm9KZM5Pew+SMoH4lvAV0BSX5DcHwln83rjKP5/fTnNw28OwvJ5MCd0GS2y/7mTXsWdH+dARYF6gmQQfwJ+cVnjNUxJlQtZY6I0XniDy7ZYrWLecYx409NlQBdI5ZLtFW4SLbDKarHVg4wf82qjc9xvErMLRLrgQ6LIkdCK8HQq506C26fEF2PHEkgMboelNwi8aagGx4Ce0zFq3xO45pxQqR/9J+RVI1anZX0tIm20ul jameswhite@Jamess-MacBook-Pro.local
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDt1d4yn+Ka1a5BrnwJ8QI0SiuxLSyH2RfctoPGWZzlxElm0L22DnEj3spMpR8m4K6ErUFz8ICRHyJ+0bj3KqeFUfVc1EVZbaY6B9/QdaSSm9KZM5Pew+SMoH4lvAV0BSX5DcHwln83rjKP5/fTnNw28OwvJ5MCd0GS2y/7mTXsWdH+dARYF6gmQQfwJ+cVnjNUxJlQtZY6I0XniDy7ZYrWLecYx409NlQBdI5ZLtFW4SLbDKarHVg4wf82qjc9xvErMLRLrgQ6LIkdCK8HQq506C26fEF2PHEkgMboelNwi8aagGx4Ce0zFq3xO45pxQqR/9J+RVI1anZX0tIm20ul jameswhite@Jamess-MacBook-Pro.local
EOF
chmod 640 $target/root/.ssh/authorized_keys

cat<<EOF > $target/root/add_opt
#!/bin/bash
/usr/sbin/groupadd --gid 400 opt
/usr/sbin/useradd --uid 400 --gid 400 -m --home-dir /home/opt --comment "Optional Software Administrator" --shell /bin/bash opt
/bin/echo "opt:fai" | /usr/sbin/chpasswd
EOF
chmod 755 $target/root/add_opt
/usr/sbin/chroot $target /root/add_opt
/bin/rm $target/root/add_opt

/bin/cp $target/etc/gdm3/daemon.conf $target/etc/gdm3/daemon.conf.dist
/bin/sed -ie 's/\[security\]/[security]\nDisallowTCP=false/' $target/etc/gdm3/daemon.conf


# get rid of fat gnome title bars
# sed -i "/title_vertical_pad/s/value=\"[0-9]\{1,2\}\"/value=\"0\"/g" /usr/share/themes/Adwaita/metacity-1/metacity-theme-3.xml

/bin/mkdir -p $target/etc/ldap/ssl
/bin/cp $FAI/files/etc/ldap/ldap.conf.tpl $target/etc/ldap/ldap.conf.tpl
/bin/sed -e "s/~ANON_SECRET~/${ANON_SECRET}/g" $target/etc/ldap/ldap.conf.tpl > $target/etc/ldap/ldap.conf
/bin/cp $FAI/files/etc/ldap/ssl/domain_trustchain.pem $target/etc/ldap/ssl/domain_trustchain.pem
/bin/cp $FAI/files/etc/nsswitch.conf $target/etc/nsswitch.conf
(cd $target/etc; mv libnss-ldap.conf libnss-ldap.conf.dist; ln -s ldap/ldap.conf libnss-ldap.conf )
(cd $target/etc; mv pam_ldap.conf pam_ldap.conf.dist;       ln -s ldap/ldap.conf pam_ldap.conf )
