#!/bin/sh
set -e
# -o pipefail is not valid in /bin/sh

echo "bugfixes"
[ ! -d /boot ] && mkdir -p /boot
[ ! -d /run/cryptsetup ] && mkdir -p /run/cryptsetup
[ -f /etc/lvm/lvm.conf ] && rm /etc/lvm/lvm.conf

echo "getting our hostname from dhcp"
[ ! -f /tmp/dhclient.eth0.dhcpopts ] && dhclient eth0
DHCPHOST="$(grep "^new_host_name=" /tmp/dhclient.eth0.dhcpopts | sed -e 's/.*=//')"
[ -z "${DHCPHOST}" ] && DHCPHOST='localhost'
echo
echo "DHCPHOST is ${DHCPHOST}"
mount | grep -q "/boot" || mount -t ext3 /dev/sda1 /boot
echo
echo "/boot/${DHCPHOST}/crypttab follows"
cat /boot/${DHCPHOST}/crypttab
echo
echo "activating all of our encrypted volumes"
cat /boot/${DHCPHOST}/crypttab | while read cryptdev blockdev keyfile type; do
  echo "keyfile is ${keyfile}"
  COMMAND="cryptsetup --type plain --cipher=aes-xts-plain64 --key-size=512 --key-file=/boot/${DHCPHOST}/crypt_dev_sda2 --offset=0 open /dev/sda2 crypt_dev_sda2"
  echo -- "${COMMAND}"
  [ ! -h /dev/mapper/${cryptdev} ] && echo 'YES' | ${COMMAND}
done

echo
echo "kicking LVM in the ass"
lvm pvscan && lvm vgscan && lvm lvscan && lvm vgchange -ay

echo
echo "mounting that shit"
set -x
mount | grep sysroot || mount -t ext4 /dev/mapper/vg0-root /sysroot || exit 1
mount | grep tmp     || mount -t ext4 /dev/mapper/vg0-tmp /sysroot/tmp
mount | grep var     || mount -t ext4 /dev/mapper/vg0-var /sysroot/var
mount | grep opt     || [ -h /dev/mapper/vg_opt-opt ] && mount -t ext4 /dev/mapper/vg_opt-opt /sysroot/opt || mount -t ext4 /dev/mapper/vg0-opt /sysroot/opt
umount /boot         && mount /dev/sda1 /sysroot/boot
set +x

echo
echo "finish setup-storage"

exit 0
