#!/bin/bash
/bin/bash 
HOSTNAME=$(/bin/hostname -s)
case "${HOSTNAME}" in
  pink)
      echo "shelling out"
      /bin/bash
      exit 0;
  ;;
  *)
      echo "shell 2"
      /bin/bash
  ;;
esac
echo "shell 3"
/bin/bash
