#!/bin/bash
# get some correct time up in here.
/usr/sbin/ntpdate 0.pool.ntp.org
/sbin/hwclock --systohc

HOSTNAME=$(/bin/hostname -s)
case "${HOSTNAME}" in
  pink|black)
      /bin/bash
      exit 0;
  ;;
  *)
      # these are our wifi sniffing boxes, they get installed via regular fai
      echo "shelling out"
      /bin/bash
  ;;
esac
exit 1;

