#!/bin/bash
# get some correct time up in here.
/usr/sbin/ntpdate 0.pool.ntp.org
/sbin/hwclock --systohc

HOSTNAME=$(/bin/hostname -s)
case "${HOSTNAME}" in
  *)
      # these are our wifi sniffing boxes, they get installed via regular fai
      #/bin/bash
      exit 0;
  ;;
esac
exit 0;

