#! /bin/bash

# assign classes hosts
/etc/init.d/open-vm-tools start > /dev/null 2>&1

# use a list of classes for our demo machine
case $HOSTNAME in
#    faiserver)
#	echo "FAIBASE DEMO FAISERVER" ;;
#    demohost)
#	echo "FAIBASE DHCPC DEMO" ;;
#    gnomehost)
#	echo "FAIBASE DHCPC DEMO XORG GNOME";;
#    secure)
#	echo "SECURE DHCPC DEMO XORG GNOME";;
#    cryptws)
#	echo "CRYPTWS DHCPC DEMO XORG GNOME";;
#    lofn|columbia)
#	echo "CRYPTWS DHCPC XORG GNOME";;
#    soekris)
#	echo "SOEKRIS DHCPC DEMO XORG GNOME";;
    audhumla)
	echo "SOEKRIS" ;;
    black)
	echo "FAIBASE DHCPC" ;;
    pink|mars)
	echo "WHEEZY GRUB_LEGACY DELL_MINI9_16GB" ;;
    oppenheimer|planck|einstein|pascal|butters|clarke|wilford)
	echo "CRYPT_SERVER CRYPT_SERVER_60G" ;;
    eir|eir.apartment.jameswhite.org)
	echo "CRYPT_SERVER CRYPT_SERVER_60G BUSTER" ;;
    octoprint|euler)
	echo "CRYPT_SERVER CRYPT_SERVER_20G" ;;
    curie.hq.thebikeshed.io|curie)
	echo "STRETCH" ;;
    *)
	echo "BUSTER" ;;
esac

# (ifclass I386 || ifclass AMD64) && echo GRUB
exit 0
