#! /bin/bash

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
#    faiserver)
#	echo "FAIBASE DEMO FAISERVER" ;;
#    demohost)
#	echo "FAIBASE DHCPC DEMO" ;;
#    gnomehost)
#	echo "FAIBASE DHCPC DEMO XORG GNOME";;
#    secure)
#	echo "SECURE DHCPC DEMO XORG GNOME";;
#    cryptws)
#	echo "CRYPTWS DHCPC DEMO XORG GNOME";;
#    lofn|columbia)
#	echo "CRYPTWS DHCPC XORG GNOME";;
#    soekris)
#	echo "SOEKRIS DHCPC DEMO XORG GNOME";;
    audhumla)
	echo "SOEKRIS" ;;
    black)
	echo "FAIBASE DHCPC" ;;
    pink|mars)
	echo "CRYPTWS DHCPC" ;;
    eir|oppenheimer|planck)
	echo "CRYPT_LAPTOP" ;;
    *)
	echo "POTATO DHCPC" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB
exit 0
